[graph]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
all-features = true

[advisories]
version = 2
yanked = "deny"
ignore = []

[licenses]
version = 2
allow = [
  "GPL-3.0-only",
  "MIT",
  "Apache-2.0",
  "0BSD",
  "Unicode-3.0",
  "Zlib",
]
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
